---
service: mtg-ai

frameworkVersion: "^1.32.0"

plugins:
  - serverless-domain-manager
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: ${env:AWS_DEFAULT_REGION, 'us-east-1'}
  stage: ${opt:stage, env:SERVERLESS_STAGE, 'dev'}
  environment:
    NODE_ENV: production

custom:
  domain: razorx.app
  subdomain: mtg.ai
  customDomain:
    domainName: ${self:provider.stage}.${self:custom.subdomain}.${self:custom.domain}
    endpointType: regional
    createRoute53Record: true
  webpack:
    packager: yarn
    includeModules:
      forceExclude:
        - aws-sdk

package:
  individually: true

functions:
  assistant:
    handler: handlers/fulfillment.default
    events:
      - http:
          method: post
          path: /fulfillment
          private: true
