---
version: 2

jobs:
  build:
    docker:
      - image: node:carbon
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: npm-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: npm-{{ checksum "package-lock.json" }}
          paths: ~/.npm
      - run:
          name: Test
          command: npm test
      - deploy:
          name: Deploy
          command: |
            if [[ -z "${CI_PULL_REQUEST}" && "${CIRCLE_BRANCH}" == "master" ]]; then
              stage="dev"
              if [[ -n "${CIRCLE_TAG}" ]]; then
                stage="alpha"
              fi
              npm run deploy --stage $stage
            else
              npm run package
            fi

workflows:
  version: 2
  default:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
