---
version: 2

jobs:
  graphql:
    working_directory: ~/project
    docker:
      - image: circleci/clojure:lein
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: m2-{{ arch }}-{{ checksum "graphql/project.clj" }}
      - run:
          name: Install dependencies
          working_directory: ~/project/graphql
          command: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: m2-{{ arch}}-{{ checksum "graphql/project.clj" }}
      - run:
          name: Build JAR
          working_directory: ~/project/graphql
          command: lein uberjar
      - persist_to_workspace:
          root: .
          paths:
            - graphql/target

  serverless-graphql:
    docker:
      - image: node
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Move target to working directory
          command: mv /tmp/workspace/graphql/target graphql
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install -g npm@6
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths: ~/.npm
      - run:
          name: Package
          working_directory: ~/project/graphql
          command: npx serverless package
      - deploy:
          name: Deploy
          working_directory: ~/project/graphql
          command: npx serverless deploy --aws-s3-accelerate
      - store_artifacts:
          path: graphql/target/mtg-gql-standalone.jar
          destination: mtg-gql-standalone.jar

workflows:
  version: 2
  default:
    jobs:
      - graphql
      - serverless-graphql
          filters:
            branches:
              only: master
          requires:
            - graphql
