---
version: 2

jobs:
  build:
    docker:
      - image: node:carbon
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: npm-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install -g npm@6
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: npm-{{ checksum "package.json" }}
          paths: ~/.npm
      - run:
          name: Test
          command: npm test
      - run:
          name: Package
          command: npx serverless package
      - deploy:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npx serverless deploy --aws-s3-accelerate
            fi
