---
version: 2

jobs:
  build:
    docker:
      - image: node:carbon
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: npm-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm
          command: npm install -g npm@6
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: npm-{{ checksum "package-lock.json" }}
          paths: ~/.npm
      - run:
          name: Test
          command: npm test
      - deploy:
          name: Deploy
          command: |
            if [[ -z "${CI_PULL_REQUEST}" && "${CIRCLE_BRANCH}" == "master" ]]; then
              npm run deploy
            else
              npm run package
            fi
