---
version: 2

jobs:
  gql:
    working_directory: ~/project
    docker:
      - image: circleci/clojure:lein
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: m2-{{ arch }}-{{ checksum "gql/project.clj" }}
      - run:
          name: Install dependencies
          working_directory: ~/project/gql
          command: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: m2-{{ arch}}-{{ checksum "gql/project.clj" }}
      - run:
          name: Build JAR
          working_directory: ~/project/gql
          command: lein uberjar
      - persist_to_workspace:
          root: .
          paths:
            - gql/target

  gql-deploy:
    docker:
      - image: node
    working_directory: ~/build
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Move target to working directory
          command: mv /tmp/workspace/gql/target gql
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths: ~/.npm
      - run:
          name: Package
          working_directory: ~/project/gql
          command: npx serverless package
      - deploy:
          name: Deploy
          working_directory: ~/project/gql
          command: npx serverless deploy
      - store_artifacts:
          path: gql/target/mtg-gql-standalone.jar
          destination: gql

workflows:
  version: 2
  default:
    jobs:
      - gql
      - gql-deploy:
          filters:
            branches:
              only: master
          requires:
            - gql
