---
version: 2

jobs:
  build:
    docker:
      - image: node:carbon
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: npm-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: npm-{{ checksum "package.json" }}
          paths: ~/.npm
      - run:
          name: Test
          command: npm test
      - deploy:
          name: Deploy
          command: |
            if [[ -z "${CI_PULL_REQUEST}" && "${CIRCLE_BRANCH}" == "master" ]]; then
              npx serverless deploy --aws-s3-accelerate
            else
              npx serverless package
            fi
